export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';


export const TRANSAKSI_LOADING = 'TRANSAKSI_LOADING';
export const GET_TRANSAKSIS = 'GET_TRANSAKSIS';
export const GET_TRANSAKSI = 'GET_TRANSAKSI';
export const DELETE_TRANSAKSI = 'DELETE_TRANSAKSI';
